language: scala
scala:
- 2.12.4
before_install:
- openssl aes-256-cbc -K $encrypted_4417123d0385_key -iv $encrypted_4417123d0385_iv
  -in google_application_credentials.json.enc -out /tmp/google_application_credentials.json
  -d
